/*:
* @requiredAssets img/system/Window
* @requiredAssets img/system/IconSet
* @requiredAssets img/system/Balloon
* @requiredAssets img/system/Shadow1
* @requiredAssets img/system/Shadow2
* @requiredAssets img/system/Damage
* @requiredAssets img/system/States
* @requiredAssets img/system/Weapons1
* @requiredAssets img/system/Weapons2
* @requiredAssets img/system/Weapons3
* @requiredAssets img/system/ButtonSet
* @requiredAssets audio/se/Cursor2
* @requiredAssets audio/se/Decision1
* @requiredAssets audio/se/Cancel2
* @requiredAssets audio/se/Buzzer1
* @requiredAssets img/titles1/Castle
* @requiredAssets audio/bgm/Theme6
* @requiredAssets img/tilesets/Inside_A1
* @requiredAssets img/tilesets/Inside_A2
* @requiredAssets img/tilesets/Inside_A4
* @requiredAssets img/tilesets/Inside_A5
* @requiredAssets img/tilesets/Inside_B
* @requiredAssets img/tilesets/Inside_C
* @requiredAssets img/characters/!$Gate1
* @requiredAssets img/characters/Vehicle
* @requiredAssets img/characters/Actor1
* @requiredAssets audio/bgm/Ship2
* @requiredAssets img/faces/Actor1
*/